name: supa_blog_files
description: Personal blog-like file storage by user with Supabase
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  file_picker: ^8.0.3
  path_provider: ^2.1.4
  open_filex: ^4.4.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  intl: ^0.19.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
